version: "3.7"
services:
  # php:
  #   build: '.docker/php/'
  #   volumes:
  #     - .:/var/www/html/

  apache:
    build: '.docker/apache/'

    ports:
      - "80:80"
    volumes:
      - .:/var/www/html/